# Generated by Django 5.1.4 on 2025-01-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpsoftware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
