# Generated by Django 5.1.4 on 2025-01-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpsoftware', '0002_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
