# Generated by Django 5.1.4 on 2025-01-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpsoftware', '0003_alter_mainimage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(blank=True, max_length=1000, null=True)),
                ('image2', models.CharField(blank=True, max_length=1000, null=True)),
                ('image3', models.CharField(blank=True, max_length=1000, null=True)),
                ('image4', models.CharField(blank=True, max_length=1000, null=True)),
                ('image5', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tools Images',
            },
        ),
    ]
