# Generated by Django 5.1.4 on 2025-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpsoftware', '0004_tools_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools_images',
            name='image6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
